name: ASCENDED BLACK DESERT ONLINE
favicon: null
layout_spectrum: 0.74682
typography_spectrum: 0.3333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20232a'
    - '#757c8e'
    - '#393d49'
    - '#eeeeee'
    - '#b1b2b4'
  brandStrength: 0
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
