analytics: {}
color:
  brandColors:
    - '#20232a'
    - '#757c8e'
    - '#393d49'
    - '#eeeeee'
    - '#b1b2b4'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.493243
  saturation: 0.875
cta: {}
layout_spectrum: 0.74737
name: ASCENDED BLACK DESERT ONLINE
opengraph: {}
purpose: []
typography_spectrum: 0.31944
