analytics: {}
color:
  brandColors:
    - '#20232a'
    - '#757c8e'
    - '#393d49'
    - '#eeeeee'
    - '#b1b2b4'
  brandStrength: 0.063345
  lightness: 0.5
  rhythmicContrast: 0.758446
  saturation: 0.771115
cta: {}
layout_spectrum: 0.608108
name: ASCENDED BLACK DESERT ONLINE
opengraph: {}
purpose: []
typography_spectrum: 0.31944
