name: ASCENDED BLACK DESERT ONLINE
favicon: null
layout_spectrum: 0.608108
typography_spectrum: 0.31944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20232a'
    - '#757c8e'
    - '#393d49'
    - '#eeeeee'
    - '#b1b2b4'
  brandStrength: 0.063345
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.758446
purpose: []
